import { useState } from "react";
import { NavLink } from "react-router-dom";
import { FaEye, FaEyeSlash, FaBuilding } from "react-icons/fa";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import authHooks from "@/hooks/useAuth";
import { USER_TYPES } from "@/constants";

// Zod Schema - matches with Backend validation (user_name is now auto-generated)
const registerSchema = z.object({
  full_name: z
    .string()
    .min(3, "Full Name must be at least 3 characters")
    .max(30, "Full Name must be at most 30 characters"),

  email: z.string().email("Please enter a valid email address"),

  password: z.string().min(6, "Password must be at least 6 characters"),

  user_type: z.enum([USER_TYPES.USER], {
    message: "User Type is required",
  }),

  agree_to_terms: z.literal(true, "You must agree to the terms"),
});

// TypeScript type infer from Zod schema
type RegisterFormData = z.infer<typeof registerSchema>;

const Register = () => {
  const { mutate: register, isPending } = authHooks.useRegister();
  const [showPassword, setShowPassword] = useState(false);

  // React Hook Form with Zod resolver
  const {
    register: registerField,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      full_name: "",
      email: "",
      password: "",
      user_type: USER_TYPES.USER,
      agree_to_terms: undefined,
    },
  });

  // Form submit handler
  const onSubmit = (registerData: RegisterFormData) => {
    // user_name will be auto-generated by Postgre Trigger
    register(registerData);
  };

  return (
    <div className="mx-auto flex w-full max-w-sm flex-col items-center justify-center gap-2.5 py-1 sm:max-w-md sm:gap-6 sm:py-6 lg:max-w-5xl lg:flex-row lg:gap-16">
      {/* Header - Left Side */}
      <div className="text-center lg:text-left">
        <h1 className="text-2xl font-extrabold text-blue-600 sm:text-4xl lg:mb-2 lg:text-5xl">
          Take Rest
        </h1>
        <h2 className="hidden text-xl font-semibold text-gray-800 sm:block sm:text-2xl lg:mb-2 lg:text-3xl">
          Create Account
        </h2>
        <p className="text-xs text-gray-500 sm:text-sm lg:text-base">
          Sign up to join the community
        </p>
      </div>

      {/* Register Form - Right Side */}
      <div className="w-full max-w-sm sm:max-w-105">
        <div className="w-full rounded-2xl border border-gray-100 bg-white p-4.5 shadow-lg sm:p-8 sm:shadow-xl">
          <form
            onSubmit={handleSubmit(onSubmit)}
            className="space-y-3 sm:space-y-5"
          >
            <div className="space-y-2.5 sm:space-y-3.5">
              {/* Full Name Field */}
              <div>
                <label
                  htmlFor="full_name"
                  className="mb-1 block text-xs font-medium text-gray-700 sm:text-sm"
                >
                  Full Name
                </label>
                <input
                  id="full_name"
                  type="text"
                  {...registerField("full_name")}
                  className={`w-full rounded-lg border px-3 py-2 text-xs transition-colors focus:ring-2 focus:outline-none sm:text-sm ${
                    errors.full_name
                      ? "border-red-500 focus:ring-red-500"
                      : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                  }`}
                  placeholder="Enter your full name"
                />
                {errors.full_name && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.full_name.message}
                  </p>
                )}
              </div>

              {/* Email Field */}
              <div>
                <label
                  htmlFor="email"
                  className="mb-1 block text-xs font-medium text-gray-700 sm:text-sm"
                >
                  Email Address
                </label>
                <input
                  id="email"
                  type="email"
                  {...registerField("email")}
                  className={`w-full rounded-lg border px-3 py-2 text-xs transition-colors focus:ring-2 focus:outline-none sm:text-sm ${
                    errors.email
                      ? "border-red-500 focus:ring-red-500"
                      : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                  }`}
                  placeholder="Enter your email"
                />
                {errors.email && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.email.message}
                  </p>
                )}
              </div>

              {/* Password Field */}
              <div>
                <label
                  htmlFor="password"
                  className="mb-1 block text-xs font-medium text-gray-700 sm:text-sm"
                >
                  Password
                </label>
                <div className="relative">
                  <input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    {...registerField("password")}
                    className={`w-full rounded-lg border px-3 py-2 pr-10 text-xs transition-colors focus:ring-2 focus:outline-none sm:text-sm ${
                      errors.password
                        ? "border-red-500 focus:ring-red-500"
                        : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                    }`}
                    placeholder="Create a password (min 6 characters)"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute inset-y-0 right-0 flex items-center pr-3 text-gray-400 hover:text-gray-600"
                  >
                    {showPassword ? (
                      <FaEyeSlash className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
                    ) : (
                      <FaEye className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
                    )}
                  </button>
                </div>
                {errors.password && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.password.message}
                  </p>
                )}
              </div>
            </div>

            {/* Terms Agreement */}
            <div>
              <div className="flex items-start">
                <input
                  id="agree_to_terms"
                  type="checkbox"
                  {...registerField("agree_to_terms")}
                  className="mt-0.5 h-3.5 w-3.5 rounded border-gray-300 text-blue-600 focus:ring-blue-500 sm:h-4 sm:w-4"
                />
                <label
                  htmlFor="agree_to_terms"
                  className="ml-2 block text-xs text-gray-600 sm:text-sm"
                >
                  I agree to the{" "}
                  <NavLink
                    to="/terms"
                    className="font-medium text-blue-600 hover:text-blue-500"
                  >
                    Terms
                  </NavLink>{" "}
                  and{" "}
                  <NavLink
                    to="/privacy"
                    className="font-medium text-blue-600 hover:text-blue-500"
                  >
                    Privacy Policy
                  </NavLink>
                </label>
              </div>
              {errors.agree_to_terms && (
                <p className="mt-1 text-xs text-red-500">
                  {errors.agree_to_terms.message}
                </p>
              )}
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isPending}
              className="w-full rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-blue-700 disabled:opacity-60 sm:py-2.5 sm:text-sm"
            >
              {isPending ? (
                <div className="flex items-center justify-center">
                  <div className="mr-2 h-3.5 w-3.5 animate-spin rounded-full border-b-2 border-white"></div>
                  Creating account...
                </div>
              ) : (
                "Create Account"
              )}
            </button>
          </form>

          {/* Login NavLink */}
          <div className="mt-3 text-center sm:mt-5">
            <p className="text-xs text-gray-600 sm:text-sm">
              Already have an account?{" "}
              <NavLink
                to="/login"
                className="font-medium text-blue-600 hover:text-blue-500"
              >
                Sign in here
              </NavLink>
            </p>
          </div>

          {/* Browse Branches (Public Access) */}
          <div className="mt-3 border-t border-gray-100 pt-3 sm:mt-5 sm:pt-5">
            <NavLink
              to="/branch"
              className="group flex w-full items-center justify-center gap-2 rounded-xl border border-gray-200/90 bg-gray-50/70 px-3.5 py-2 text-xs font-semibold text-gray-700 shadow-2xs transition-all duration-200 hover:border-blue-300 hover:bg-blue-50/80 hover:text-blue-700 hover:shadow-xs active:scale-98 sm:py-2.5 sm:text-sm"
            >
              <FaBuilding className="h-3.5 w-3.5 text-blue-600 transition-transform duration-200 group-hover:scale-110 sm:h-4 sm:w-4" />
              <span>View Branches</span>
            </NavLink>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
