import { useState } from "react";
import { NavLink } from "react-router-dom";
import { FaEye, FaEyeSlash } from "react-icons/fa";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import authHooks from "@/hooks/useAuth";
import { USER_TYPES } from "@/constants";

// Zod Schema - matches with Backend validation (user_name is now auto-generated)
const registerSchema = z.object({
  full_name: z
    .string()
    .min(3, "Full Name must be at least 3 characters")
    .max(30, "Full Name must be at most 30 characters"),

  email: z.string().email("Please enter a valid email address"),

  password: z.string().min(6, "Password must be at least 6 characters"),

  user_type: z.enum([USER_TYPES.USER], {
    message: "User Type is required",
  }),

  agree_to_terms: z.literal(true, "You must agree to the terms"),
});

// TypeScript type infer from Zod schema
type RegisterFormData = z.infer<typeof registerSchema>;

const Register = () => {
  const { mutate: register, isPending } = authHooks.useRegister();
  const [showPassword, setShowPassword] = useState(false);

  // React Hook Form with Zod resolver
  const {
    register: registerField,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      full_name: "",
      email: "",
      password: "",
      user_type: USER_TYPES.USER,
      agree_to_terms: undefined,
    },
  });

  // Form submit handler
  const onSubmit = (registerData: RegisterFormData) => {
    // user_name will be auto-generated by Postgre Trigger
    register(registerData);
  };

  return (
    <div className="flex h-screen w-full flex-col items-center gap-3 p-3 lg:flex-row lg:justify-center lg:gap-15 lg:p-0">
      {/* Header - Left Side */}
      <div className="text-center lg:text-left">
        <h1 className="mb-2 text-4xl font-bold text-blue-600 lg:text-5xl">
          Take Rest
        </h1>
        <h2 className="mb-2 text-2xl font-semibold text-gray-800 lg:text-3xl">
          Create Account
        </h2>
        <p className="text-sm text-gray-600 sm:text-base">
          Sign up to join the community
        </p>
      </div>

      {/* Register Form - Right Side */}
      <div className="w-full max-w-[400px] rounded-lg border bg-white p-5 shadow-lg lg:max-w-[550px]">
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
          {/* Scrollable Input Fields */}
          <div className="space-y-3 overflow-y-auto p-2">
            {/* Full Name Field */}
            <div>
              <label
                htmlFor="full_name"
                className="mb-2 block text-sm font-medium text-gray-700"
              >
                Full Name
              </label>
              <input
                id="full_name"
                type="text"
                {...registerField("full_name")}
                className={`w-full rounded-lg border px-3 py-2 transition-colors focus:ring-2 focus:outline-none ${
                  errors.full_name
                    ? "border-red-500 focus:ring-red-500"
                    : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                }`}
                placeholder="Enter your full name"
              />
              {errors.full_name && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.full_name.message}
                </p>
              )}
            </div>

            {/* Email Field */}
            <div>
              <label
                htmlFor="email"
                className="mb-2 block text-sm font-medium text-gray-700"
              >
                Email Address
              </label>
              <input
                id="email"
                type="email"
                {...registerField("email")}
                className={`w-full rounded-lg border px-3 py-2 transition-colors focus:ring-2 focus:outline-none ${
                  errors.email
                    ? "border-red-500 focus:ring-red-500"
                    : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                }`}
                placeholder="Enter your email"
              />
              {errors.email && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.email.message}
                </p>
              )}
            </div>

            {/* user_name Field - auto generated by backend - keep it for legacy purpose only  */}
            {/* <div>
              <label
                htmlFor="user_name"
                className="mb-2 block text-sm font-medium text-gray-700"
              >
                user_name
              </label>
              <input
                id="user_name"
                type="text"
                {...registerField("user_name")}
                className={`w-full rounded-lg border px-3 py-2 transition-colors focus:ring-2 focus:outline-none ${
                  errors.user_name
                    ? "border-red-500 focus:ring-red-500"
                    : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                }`}
                placeholder="Choose a user_name (e.g., user_123)"
              />
              {errors.user_name && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.user_name.message}
                </p>
              )}
            </div> */}

            {/* User Type Field */}
            <div className="hidden">
              <label
                htmlFor="UserType"
                className="mb-2 block text-sm font-medium text-gray-700"
              >
                I am a
              </label>
              <select
                id="UserType"
                {...registerField("user_type")}
                className={`w-full appearance-none rounded-lg border px-3 py-2 transition-colors focus:ring-2 focus:outline-none ${
                  errors.user_type
                    ? "border-red-500 focus:ring-red-500"
                    : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                }`}
              >
                <option value={USER_TYPES.USER}>User</option>
              </select>
              {errors.user_type && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.user_type.message}
                </p>
              )}
            </div>

            {/* Password Field */}
            <div>
              <label
                htmlFor="password"
                className="mb-2 block text-sm font-medium text-gray-700"
              >
                Password
              </label>
              <div className="relative">
                <input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  {...registerField("password")}
                  className={`w-full rounded-lg border px-3 py-2 pr-10 transition-colors focus:ring-2 focus:outline-none ${
                    errors.password
                      ? "border-red-500 focus:ring-red-500"
                      : "border-gray-300 focus:border-blue-500 focus:ring-blue-500"
                  }`}
                  placeholder="Create a password"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute inset-y-0 right-0 flex items-center pr-3 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <FaEyeSlash /> : <FaEye />}
                </button>
              </div>
              {errors.password && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.password.message}
                </p>
              )}
            </div>
          </div>

          {/* Terms Agreement */}
          <div>
            <div className="flex items-start">
              <input
                id="agree_to_terms"
                type="checkbox"
                {...registerField("agree_to_terms")}
                className="mt-0.5 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
              />
              <label
                htmlFor="agree_to_terms"
                className="ml-2 block text-sm font-medium text-gray-700"
              >
                I agree to the{" "}
                <NavLink
                  to="/terms"
                  className="text-blue-600 hover:text-blue-500"
                >
                  Terms of Service
                </NavLink>{" "}
                and{" "}
                <NavLink
                  to="/privacy"
                  className="text-blue-600 hover:text-blue-500"
                >
                  Privacy Policy
                </NavLink>
              </label>
            </div>
            {errors.agree_to_terms && (
              <p className="mt-1 text-sm text-red-500">
                {errors.agree_to_terms.message}
              </p>
            )}
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            disabled={isPending}
            className="w-full rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700 disabled:opacity-60"
          >
            {isPending ? (
              <div className="flex items-center justify-center">
                <div className="mr-2 h-4 w-4 animate-spin rounded-full border-b-2 border-white"></div>
                Creating account...
              </div>
            ) : (
              "Create Account"
            )}
          </button>
        </form>

        {/* Login NavLink */}
        <div className="mt-3 text-center">
          <p className="text-sm text-gray-600">
            Already have an account?{" "}
            <NavLink
              to="/login"
              className="font-medium text-blue-600 hover:text-blue-500"
            >
              Sign in here
            </NavLink>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Register;
