const AUTH_KEYS = {
  CURRENT_USER: "CURRENT_USER",
} as const;

const BRANCH_KEYS = {
  MY_BRANCHES: "MY_BRANCHES",
  DETAILS: "BRANCH_DETAILS",
  MEMBERS: "BRANCH_MEMBERS",
  SEARCH: "BRANCH_SEARCH",
} as const;

const FINANCE_KEYS = {
  SUMMARY: "FINANCE_SUMMARY",
  CATEGORIES: "FINANCE_CATEGORIES",
  CATEGORIES_LIST: "FINANCE_CATEGORIES_LIST",
  ENTRIES: "FINANCE_ENTRIES",
  MONTH_EXPORT: "FINANCE_MONTH_EXPORT",
  PAYMENTS: "FINANCE_PAYMENTS",
} as const;

export { AUTH_KEYS, BRANCH_KEYS, FINANCE_KEYS };
